name: Build and Publish image to Docker Hub
on:
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build ./api/ -t isirakatakumbura/devops-qr-code-generator-api:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push image to docker Hub
        run: |
          docker push isirakatakumbura/devops-qr-code-generator-api:latest

